import { StyleSheet } from "@react-pdf/renderer";
import { getPdfTheme } from "../data/pdfThemes";

export const createPdfStyles = (themeValue = "light") => {
  const c = getPdfTheme(themeValue).pdf;

  return StyleSheet.create({
    page: {
      flexDirection: "column",
      backgroundColor: c.bg,
      padding: 24,
      fontFamily: "Helvetica",
      fontSize: 14,
      lineHeight: 1.4,
      color: c.text,
    },
    invoiceTitle: {
      fontSize: 20,
      fontWeight: "normal",
      textTransform: "uppercase",
      color: c.title,
      marginBottom: 16,
      textAlign: "left",
    },
    headerSection: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderStyle: "dashed",
      borderColor: c.border,
      paddingTop: 12,
      paddingBottom: 4,
      position: "relative",
    },
    headerDivider: {
      position: "absolute",
      left: "50%",
      top: 0,
      bottom: 0,
      borderLeftWidth: 1,
      borderStyle: "dashed",
      borderColor: c.border,
    },
    headerLeft: { width: "48%", paddingRight: 6, fontSize: 11 },
    headerRight: {
      width: "48%",
      alignItems: "flex-end",
      justifyContent: "center",
      paddingLeft: 6,
    },
    headerRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginVertical: 1,
    },
    headerLabel: { color: c.label, fontSize: 11 },
    headerValue: { color: c.text, fontSize: 11, marginLeft: 8 },
    logo: { maxHeight: 60, objectFit: "contain" },
    billingSection: {
      flexDirection: "row",
      justifyContent: "space-between",
      borderBottomWidth: 1,
      borderStyle: "dashed",
      borderColor: c.border,
      marginBottom: 16,
      paddingTop: 12,
      paddingBottom: 4,
      position: "relative",
    },
    billingDivider: {
      position: "absolute",
      left: "50%",
      top: 0,
      bottom: 0,
      borderLeftWidth: 1,
      borderStyle: "dashed",
      borderColor: c.border,
    },
    billingColumn: { width: "48%" },
    billingHeader: { fontSize: 11, fontWeight: 500, color: c.title, marginBottom: 4 },
    billingText: { fontSize: 11, color: c.muted, lineHeight: 1.5, marginBottom: 4 },
    customFieldsContainer: {
      marginTop: 8,
      paddingTop: 8,
      borderTopWidth: 1,
      borderStyle: "dashed",
      borderColor: c.borderSoft,
    },
    customField: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginVertical: 1,
    },
    customFieldLabel: { fontSize: 11, fontWeight: 500, color: c.text },
    customFieldValue: { fontSize: 11, color: c.text, marginLeft: 8 },
    itemsContainer: {},
    itemsHeader: {
      flexDirection: "row",
      backgroundColor: c.headerBg,
      fontSize: 11,
      fontWeight: 500,
      paddingTop: 6,
      paddingHorizontal: 8,
      color: c.title,
      marginBottom: 2,
      borderRadius: 4,
    },
    itemsHeaderNo: { width: "8%", textAlign: "left" },
    itemsHeaderItem: { width: "40%" },
    itemsHeaderQty: { width: "8%", textAlign: "center" },
    itemsHeaderPrice: { width: "22%", textAlign: "right" },
    itemsHeaderTotal: { width: "22%", textAlign: "right" },
    itemRow: {
      flexDirection: "row",
      borderBottomWidth: 1,
      borderStyle: "dashed",
      borderColor: c.border,
      paddingVertical: 8,
      paddingHorizontal: 8,
      alignItems: "flex-start",
    },
    itemNo: { width: "8%", fontSize: 10, color: c.muted, paddingTop: 2 },
    itemDetails: { width: "40%", paddingHorizontal: 2 },
    itemName: { fontSize: 11, fontWeight: 500, color: c.muted, marginBottom: 2 },
    itemDescription: { fontSize: 10, color: c.muted, lineHeight: 1 },
    itemQty: { width: "8%", fontSize: 10, color: c.muted, textAlign: "center", paddingTop: 2 },
    itemPrice: { width: "22%", fontSize: 10, color: c.muted, textAlign: "right", paddingTop: 2 },
    itemTotal: { width: "22%", fontSize: 10, color: c.muted, textAlign: "right", paddingTop: 2 },
    calculationSection: {
      flexDirection: "row",
      justifyContent: "flex-end",
      alignItems: "center",
      width: "100%",
      marginBottom: 12,
    },
    calculationContainer: { width: "40%" },
    calculationRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 4,
      borderBottomWidth: 1,
      borderStyle: "dashed",
      borderColor: c.borderSoft,
    },
    calculationLabel: { fontSize: 11, color: c.text },
    calculationValue: { fontSize: 11, color: c.text, paddingRight: 8 },
    totalRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderStyle: "dashed",
      borderColor: c.borderSoft,
    },
    totalLabel: { fontSize: 14, fontWeight: 500, color: c.text },
    totalValue: { fontSize: 14, fontWeight: 500, color: c.text, paddingRight: 8 },
    paymentSection: {
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "stretch",
      width: "100%",
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderStyle: "dashed",
      borderColor: c.border,
      marginBottom: 16,
      marginTop: 4,
      position: "relative",
    },
    paymentDivider: {
      position: "absolute",
      left: "50%",
      top: 0,
      bottom: 0,
      borderLeftWidth: 1,
      borderStyle: "dashed",
      borderColor: c.border,
    },
    paymentLeft: { width: "48%", paddingTop: 12, paddingBottom: 4, paddingRight: 6 },
    paymentRight: {
      width: "48%",
      paddingTop: 12,
      paddingBottom: 4,
      paddingLeft: 12,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "column",
    },
    paymentTitle: { fontSize: 11, color: c.title, fontWeight: 500, marginBottom: 6 },
    paymentRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 1,
    },
    paymentLabel: { fontSize: 11, color: c.muted },
    paymentValue: { fontSize: 11, color: c.muted },
    signatureContainer: {
      width: "100%",
      height: 60,
      paddingTop: 8,
      justifyContent: "center",
      alignItems: "center",
      flex: 1,
    },
    signature: { maxHeight: 40, maxWidth: 100, objectFit: "contain" },
    signatureTextContainer: {
      width: "100%",
      height: 24,
      justifyContent: "center",
      alignItems: "center",
    },
    signatureText: {
      fontSize: 10,
      color: c.muted,
      backgroundColor: c.headerBg,
      paddingVertical: 4,
      paddingHorizontal: 8,
      textAlign: "center",
      width: "100%",
    },
    notesSection: {
      width: "100%",
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderStyle: "dashed",
      borderColor: c.border,
      backgroundColor: c.notesBg,
      paddingVertical: 12,
      paddingHorizontal: 12,
      marginBottom: 16,
    },
    notesTitle: { color: c.title, fontWeight: 500, fontSize: 11, marginBottom: 2 },
    notesText: { color: c.muted, fontSize: 10, lineHeight: 1 },
    thankYouSection: {
      width: "100%",
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderStyle: "dashed",
      borderColor: c.border,
      backgroundColor: c.notesBg,
      paddingVertical: 12,
      paddingHorizontal: 12,
      textAlign: "center",
    },
    thankYouTitle: {
      color: c.title,
      fontWeight: 500,
      fontSize: 11,
      marginBottom: 2,
      textAlign: "center",
    },
    thankYouText: { color: c.muted, fontSize: 10, textAlign: "center" },
  });
};
